
export const LSC_UPDATE_LS_DICT = 'UPDATE_LOCAL_STORAGE';
export const LSC_UPDATE_LS_DICT_DEEP = 'DEEP_UPDATE_LOCAL_STORAGE';
export const LSC_HYDRATE_CACHE = "HYDRATE_CACHE";
export const LSC_FLUSH_CACHE = "FLUSH_CACHE";
export const LSC_RESET_CACHE = "RESET_CACHE";

export const LS_SHALLOW_MERGE = "LS_SHALLOW_MERGE";
export const LS_DEEP_MERGE = "LS_DEEP_MERGE";
export const LS_TRIGGER_FLUSH = 'TRIGGER_FLUSH';
