
name: Prod Release - care-app

on: 
  push: 
    branches: 
    - master

jobs: 
  publish: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v1 
    - name: Use Node.js 10.13.0
      uses: actions/setup-node@v1 
      with: 
        node-version: 10.13.0


    - name: npm install, build, and test 
      run: | 
        npm install 
        npm run build --if-present 
      env: 
        CI: true 
        V: 1
        REACT_APP_REG_SERVER: ${{ secrets.REACT_APP_REG_SERVER }}
        REACT_APP_FIREBASE_AUTH_CONFIG: ${{ secrets.REACT_APP_FIREBASE_AUTH_CONFIG }} 
        REACT_APP_FIREBASE_DFLT_CONFIG: ${{ secrets.REACT_APP_FIREBASE_DFLT_CONFIG }} 
        REACT_APP_MYSRCM_CONFIG: ${{ secrets.REACT_APP_MYSRCM_CONFIG }}     

#    - name: Deploy to Firebase 
#      uses: lowply/deploy-firebase@v0.0.2 
#
#      env: 
#        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
#        FIREBASE_PROJECT: xxx-xxx-xxx